# snake.yml
name: Generate a cool snake

on:
  schedule:
    # Run once a day at 11:55 UTC (adjust as needed)
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Platypus-zone/github-contribution-grid-snake@v2
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          # The file name for the generated image
          # This should be the same as the name you use in your README
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.gif
            dist/github-contribution-grid-snake-dark.svg?palette=dark

      - uses: crazy-max/ghaction-git-restore@v1
      - uses: EndBug/add-and-commit@v9
        with:
          branch: main
          message: 'Generate Contribution Snake'
          add: 'dist/github-contribution-grid-snake*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
